name: Dependency Update Bot

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install deps
        run: npm install

      - name: Update dependencies
        run: npm update

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit & Push
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --global user.name "Asad-bot07"
          git config --global user.email "asadhussain2408@gmail.com"
          git add .
          git commit -m "chore: auto update dependencies"
          git push